### ISSUE TITLE
Again error

### ISSUE THREAD

**Issue by seprj** [InverseLight/ValoMC#3]
Thank you for your response and your attention
I made the sphere_in_box.vol . but when  runing the netgentest3d  in matlab  .
I have below errors :
Error using createBH (line 33)
Cannot find mex function createBH3. It is located at cpp/3d/createBH3mex.cpp. See installation instructions how to compile it

Error in importNetGenMesh (line 160)
               vmcmesh.BH = sort(createBH(vmcmesh.H),2);

Error in netgentest3d (line 20)
[vmcmesh regions region_names boundaries boundary_names] = importNetGenMesh('sphere_in_box.vol', false);
 
How can I fix these errors?
Thank you very much for helping me

**Comment by aaleino** [comment]
Hello. You need to compile "createBH3mex". If you compile ValoMC using "CMake" it will be compiled automatically. Further instructions are in the installation guide. Alternatively you can also compile it using e.g. "mex cpp/3d/createBH3mex.cpp"  within MATLAB and making sure the resulting mex file is included in MATLAB path.
